GET http://localhost:3000/users

### Usuário Comum
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john3@doe.com",
    "password": "123"
}



### Usuário Partner
POST http://localhost:3000/partner/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john2@doe.com",
    "password": "123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "john2@doe.com",
    "password": "123"
}

###
POST http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huMkBkb2UuY29tIiwicm9sZXMiOlsiUEFSVE5FUiJdLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTE0VDIzOjU1OjI1LjY3NloiLCJ1cGRhdGVkQXQiOiIyMDI0LTA2LTE0VDIzOjU1OjI1LjY3NloiLCJpYXQiOjE3MTg0MTE3MDQsImV4cCI6MTcxODQ5ODEwNH0.yjKWlNUv-iQsaDQine1F_iKwWDwuwVeXg_CJTUVyRuY
    
{
    "name": "Partner"
}
